version: '3.8'

services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: inventario-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=inventario_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - inventario-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: inventario-app
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "7788:7788"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/inventario_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - inventario-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  inventario-network:
    driver: bridge

volumes:
  postgres-data: