version: "3"

networks:
  kafka-connect-full-net:
    name: kafka-connect-full-net
    driver: bridge

services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: postgres-development
    restart: unless-stopped
    networks:
      - kafka-connect-full-net
    ports:
     - "5432:5432"
    volumes:
      - "./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf"
      - "./postgresql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
     POSTGRES_PASSWORD: postgres