server:
  port: 7788
  servlet:
    context-path: /inventario-api

spring:
  application:
    name: inventario-hexagonal
  
  # Configuración de base de datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      pool-name: InventarioHikariCP
  
  # Configuración JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.lob.non_contextual_creation: true
    hibernate:
      ddl-auto: update # Cambiar a 'validate' en producción
  
  # Configuración de Jackson para serialización/deserialización
  jackson:
    serialization:
      fail-on-empty-beans: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Bogota

# Configuración de logging
logging:
  level:
    root: INFO
    com.litethinking.hexagonal: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"